### Récupérer les entreprises
GET http://localhost:3000/api/admin/company
Content-Type: application/json

### creation d'une entreprise
POST http://localhost:3000/api/company
Content-Type: application/json

{
    "name": "Entreprise créée",
    "siret": "51234567891234",
    "localisation": "Pau"
}

### Modification d'une entreprise
PATCH http://localhost:3000/api/company/4
Content-Type: application/json

{
    "name": "Entreprise modifiée"
}

### Suppression d'une entreprise
DELETE http://localhost:3000/api/company/1
Content-Type: application/json

